#!/bin/bash

COILSNAKE_DIR=`pwd`
ASSETS_CCSCRIPT_DIR=coilsnake/assets/ccc
CCSCRIPT_SRC_DIR=ccscript_legacy/src
CCSCRIPT_BIN_DIR=$CCSCRIPT_SRC_DIR/bin

# Clean CoilSnake
./setup.py clean
find coilsnake/ -name \*.so | xargs rm
rm -r $ASSETS_CCSCRIPT_DIR/ccc $ASSETS_CCSCRIPT_DIR/lib

# Clean CCScript
cd $CCSCRIPT_SRC_DIR
make clean
cd $COILSNAKE_DIR

# Build CoilSnake
./setup.py build_ext --inplace clean

# Build CCScript
cd $CCSCRIPT_SRC_DIR
make
cd $COILSNAKE_DIR

# Copy CCScript binaries to CoilSnake
cp -r $CCSCRIPT_BIN_DIR/ccc $CCSCRIPT_BIN_DIR/lib $ASSETS_CCSCRIPT_DIR